import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {database,memoryStorage} from '../scripts/runtime.mjs';
import {seed} from '../scripts/seed.mjs';
import {queueEmail,flushOutbox,emailHtml} from '../src/notifications.js';
import {fetchHandler} from '../src/worker.js';
import {onRequest} from '../functions/[[path]].js';
const origin='https://research.skyfirst.io.vn';
function fixture(){const {DB,sqlite}=database();return {DB,sqlite,APP_ORIGIN:origin,STORAGE:memoryStorage(),MODE:'single',RESEND_API_KEY:'unit-test-not-a-real-key'};}
async function enqueue(env){await queueEmail(env,{recipient:'qa@example.test',subject:'Test',message:'Nội dung'});}
test('Pages: canonical Pages config preserves existing DB/R2',()=>{const c=JSON.parse(readFileSync('wrangler.jsonc'));assert.equal(c.pages_build_output_dir,'./public');assert.equal(c.main,undefined);assert.equal(c.d1_databases[0].database_id,'ddcc0aa9-cbd3-4a7c-ad9d-dc226456eef1');assert.equal(c.r2_buckets[0].bucket_name,'ttrungtam');});
test('Pages: adapter fetches index asset explicitly, never context.next original route',async()=>{const env=fixture();delete env.RESEND_API_KEY;const paths=[];env.ASSETS={fetch:async r=>{paths.push(new URL(r.url).pathname);return new Response(readFileSync('public/index.html'),{headers:{'content-type':'text/html'}});}};const r=await onRequest({request:new Request(origin+'/about'),env,next:()=>{throw Error('wrong continuation');},waitUntil:()=>{}});const html=await r.text();assert.equal(r.status,200);assert.deepEqual(paths,['/']);assert.match(html,/src="\/app.js"/);assert.match(html,/<article class="article">/);assert.match(html,/href="\/style.css"/);});
test('Pages: empty entry fails visibly instead of HTTP 200 blank screen',async()=>{const env=fixture();delete env.RESEND_API_KEY;env.ASSETS={fetch:async()=>new Response('')};const r=await fetchHandler(new Request(origin),env);assert.equal(r.status,503);assert.match(await r.text(),/Pages build output/);});
test('Pages: sitemap and robots are not bypassed as arbitrary static extensions',async()=>{const env=fixture();delete env.RESEND_API_KEY;for(const path of ['/robots.txt','/sitemap.xml']){const r=await onRequest({request:new Request(origin+path),env,waitUntil:()=>{}});assert.equal(r.status,200);assert.ok((await r.text()).length>40);}});
test('Email: no provider key keeps pending job',async()=>{const env=fixture();delete env.RESEND_API_KEY;await enqueue(env);assert.equal((await flushOutbox(env)).skipped,true);assert.equal(env.sqlite.prepare('SELECT attempts FROM outbox').get().attempts,0);});
test('Email: sender, reply-to, official logo, escaped text and receipt',async()=>{const env=fixture();await enqueue(env);env.EMAIL_FETCH=async(url,init)=>{assert.equal(url,'https://api.resend.com/emails');const b=JSON.parse(init.body);assert.equal(b.from,'Sky First Research & Innovation Center <research@skyfirst.io.vn>');assert.equal(b.reply_to,'research@skyfirst.io.vn');assert.match(b.html,/sky-first-logo.png/);assert.match(init.headers['Idempotency-Key'],/^sfrc-/);return Response.json({id:'provider-test'});};assert.equal((await flushOutbox(env)).delivered,1);assert.equal(env.sqlite.prepare('SELECT provider_id FROM outbox').get().provider_id,'provider-test');assert.match(emailHtml({title:'<script>',actionUrl:'javascript:alert(1)'}),/&lt;script&gt;/);assert.doesNotMatch(emailHtml({title:'ok',actionUrl:'javascript:alert(1)'}),/href="javascript/);});
test('Email: simultaneous isolates send once under DB lease',async()=>{const env=fixture();await enqueue(env);let calls=0;env.EMAIL_FETCH=async()=>{calls++;await new Promise(r=>setTimeout(r,10));return Response.json({id:'once'});};await Promise.all([flushOutbox(env),flushOutbox(env),flushOutbox(env)]);assert.equal(calls,1);});
test('Email: rate limit backoff, Retry-After and stable retry body/key',async()=>{const env=fixture();await enqueue(env);const requests=[];env.EMAIL_FETCH=async(_,x)=>{requests.push(x);return requests.length===1?new Response('',{status:429,headers:{'retry-after':'120'}}):Response.json({id:'retry'});};await flushOutbox(env);const row=env.sqlite.prepare('SELECT * FROM outbox').get();assert.equal(row.attempts,1);assert.ok(row.next_attempt_at>=Math.floor(Date.now()/1000)+119);await flushOutbox(env);assert.equal(requests.length,1);env.sqlite.exec('UPDATE outbox SET next_attempt_at=0');await flushOutbox(env);assert.equal(requests.length,2);assert.equal(requests[0].body,requests[1].body);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);});
test('Email: permanent provider error stops retries without storing response secrets',async()=>{const env=fixture();await enqueue(env);env.EMAIL_FETCH=async()=>new Response('sensitive-provider-body',{status:422});await flushOutbox(env);const row=env.sqlite.prepare('SELECT * FROM outbox').get();assert.equal(row.status,'failed');assert.equal(row.last_error,'Resend HTTP 422');});
test('Email: five transient failures exhaust queue',async()=>{const env=fixture();await enqueue(env);env.EMAIL_FETCH=async()=>{throw Error('network unavailable')};for(let i=0;i<5;i++){env.sqlite.exec('UPDATE outbox SET next_attempt_at=0');await flushOutbox(env);}const row=env.sqlite.prepare('SELECT * FROM outbox').get();assert.equal(row.status,'failed');assert.equal(row.attempts,5);});
test('Email: expired idempotency window stops ambiguous resend',async()=>{const env=fixture();await enqueue(env);env.sqlite.exec('UPDATE outbox SET first_attempt_at=1');env.EMAIL_FETCH=()=>{throw Error('must not send')};await flushOutbox(env);assert.equal(env.sqlite.prepare('SELECT last_error FROM outbox').get().last_error,'idempotency_window_expired');});
test('Email: expired password reset is not sent and token scrubbed',async()=>{const env=fixture();await queueEmail(env,{recipient:'qa@example.test',subject:'Reset',type:'password_reset',actionUrl:origin+'/#reset/test-token',expiresAt:1});env.EMAIL_FETCH=()=>{throw Error('must not send')};await flushOutbox(env);const r=env.sqlite.prepare('SELECT * FROM outbox').get();assert.equal(r.last_error,'reset_link_expired');assert.equal(r.payload,'{}');});
test('Email: notification trigger creates correctly routed message',async()=>{const env=fixture();await seed(env.DB,crypto.randomUUID());env.sqlite.exec("DELETE FROM outbox; INSERT INTO notifications(id,user_id,title,record_id) VALUES('email-note','demo-admin','Assigned','demo-projects')");let html;env.EMAIL_FETCH=async(_,x)=>{html=JSON.parse(x.body).html;return Response.json({id:'notice'});};await flushOutbox(env);assert.match(html,/#w\/detail\/demo-projects/);});
test('Email: password reset and admin email endpoints respect RBAC and redact export',async()=>{const env=fixture();delete env.RESEND_API_KEY;const pw=crypto.randomUUID();await seed(env.DB,pw);async function call(path,method='GET',body,cookie=''){return fetchHandler(new Request(origin+'/api/v1'+path,{method,headers:{origin,'x-requested-with':'SFRC',cookie},body:body===undefined?undefined:JSON.stringify(body)}),env);}const login=await call('/login','POST',{email:'demo-admin@example.test',password:pw});const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await call('/admin/email')).status,401);const reset=await call('/admin/reset','POST',{user_id:'demo-reviewer'},cookie);assert.equal(reset.status,200);const queue=env.sqlite.prepare("SELECT payload FROM outbox WHERE subject='Liên kết đặt lại mật khẩu'").get();assert.equal(JSON.parse(queue.payload).type,'password_reset');const list=await call('/admin/email','GET',undefined,cookie);assert.doesNotMatch(await list.text(),/reset\//);const exp=await (await call('/admin/export','GET',undefined,cookie)).json();assert.ok(!exp.tables.includes('outbox'));});
test('Pages: maintenance endpoint needs strong secret and does not expose CORS',async()=>{const env=fixture();delete env.RESEND_API_KEY;assert.equal((await fetchHandler(new Request(origin+'/api/v1/maintenance',{method:'POST'}),env)).status,403);env.MAINTENANCE_SECRET=crypto.randomUUID();const r=await fetchHandler(new Request(origin+'/api/v1/maintenance',{method:'POST',headers:{authorization:'Bearer '+env.MAINTENANCE_SECRET}}),env);assert.equal(r.status,200);assert.equal(r.headers.get('access-control-allow-origin'),null);});
test('Auth: password change invalidates outstanding reset token and queued reset email',async()=>{const env=fixture();delete env.RESEND_API_KEY;const password=crypto.randomUUID();await seed(env.DB,password);const call=async(path,body,cookie='')=>fetchHandler(new Request(origin+'/api/v1'+path,{method:'POST',headers:{origin,'x-requested-with':'SFRC',cookie},body:JSON.stringify(body)}),env);const login=await call('/login',{email:'demo-admin@example.test',password});const cookie=login.headers.get('set-cookie').split(';')[0];const reset=await call('/admin/reset',{user_id:'demo-admin'},cookie);assert.equal(reset.status,200);assert.equal(env.sqlite.prepare('SELECT count(*) n FROM reset_tokens').get().n,1);assert.equal((await call('/password',{current:password,password:crypto.randomUUID()},cookie)).status,200);assert.equal(env.sqlite.prepare('SELECT count(*) n FROM reset_tokens').get().n,0);assert.equal(env.sqlite.prepare("SELECT count(*) n FROM outbox WHERE status='pending' AND json_extract(payload,'$.type')='password_reset'").get().n,0);});
test('Email: admin retry is authorized, audited, and refuses expired jobs',async()=>{const env=fixture();delete env.RESEND_API_KEY;const password=crypto.randomUUID();await seed(env.DB,password);const call=async(path,body,cookie='')=>fetchHandler(new Request(origin+'/api/v1'+path,{method:'POST',headers:{origin,'x-requested-with':'SFRC',cookie},body:JSON.stringify(body)}),env);const login=await call('/login',{email:'demo-admin@example.test',password});const cookie=login.headers.get('set-cookie').split(';')[0];await enqueue(env);env.sqlite.exec("UPDATE outbox SET status='failed',first_attempt_at=unixepoch(),attempts=5");const id=env.sqlite.prepare('SELECT id FROM outbox LIMIT 1').get().id;assert.equal((await call('/admin/email/retry',{id})).status,401);assert.equal((await call('/admin/email/retry',{id},cookie)).status,200);assert.equal(env.sqlite.prepare("SELECT count(*) n FROM audit WHERE action='email_retry'").get().n,1);env.sqlite.exec("UPDATE outbox SET status='failed',first_attempt_at=1");assert.equal((await call('/admin/email/retry',{id},cookie)).status,409);});
