PRAGMA foreign_keys=ON;
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE users(id TEXT PRIMARY KEY,email TEXT UNIQUE COLLATE NOCASE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('admin','coordinator','researcher','reviewer','finance')),active INTEGER NOT NULL DEFAULT 1,force_change INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sessions(hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX sessions_user ON sessions(user_id);
CREATE TABLE records(id TEXT PRIMARY KEY,kind TEXT NOT NULL,title TEXT NOT NULL,summary TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',owner_id TEXT NOT NULL REFERENCES users(id),project_id TEXT REFERENCES records(id),data TEXT NOT NULL DEFAULT '{}',version INTEGER NOT NULL DEFAULT 1,deleted INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX records_kind ON records(kind,deleted,status,updated_at);
CREATE INDEX records_project ON records(project_id,kind);
CREATE INDEX records_owner ON records(owner_id);
CREATE TABLE members(project_id TEXT NOT NULL REFERENCES records(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN('lead','member','advisor')),PRIMARY KEY(project_id,user_id));
CREATE TABLE reviews(id TEXT PRIMARY KEY,record_id TEXT NOT NULL REFERENCES records(id),reviewer_id TEXT NOT NULL REFERENCES users(id),round INTEGER NOT NULL DEFAULT 1,score INTEGER CHECK(score BETWEEN 0 AND 100),verdict TEXT,comment TEXT NOT NULL DEFAULT '',submitted_at TEXT,UNIQUE(record_id,reviewer_id,round));
CREATE TABLE files(id TEXT PRIMARY KEY,record_id TEXT NOT NULL REFERENCES records(id),object_key TEXT NOT NULL UNIQUE,name TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,sha256 TEXT NOT NULL,uploaded_by TEXT NOT NULL REFERENCES users(id),created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE history(id TEXT PRIMARY KEY,record_id TEXT NOT NULL REFERENCES records(id),actor_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',snapshot TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX history_record ON history(record_id,created_at);
CREATE TABLE audit(id TEXT PRIMARY KEY,actor_id TEXT,action TEXT NOT NULL,target_id TEXT,detail TEXT NOT NULL DEFAULT '{}',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TRIGGER audit_immutable_update BEFORE UPDATE ON audit BEGIN SELECT RAISE(ABORT,'immutable audit'); END;
CREATE TRIGGER audit_immutable_delete BEFORE DELETE ON audit BEGIN SELECT RAISE(ABORT,'immutable audit'); END;
CREATE TABLE notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,record_id TEXT,seen INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX notifications_user ON notifications(user_id,seen,created_at);
CREATE TABLE registrations(event_id TEXT NOT NULL REFERENCES records(id),user_id TEXT NOT NULL REFERENCES users(id),attended INTEGER NOT NULL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(event_id,user_id));
CREATE TABLE rate_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE nonces(id TEXT PRIMARY KEY,expires INTEGER NOT NULL);
CREATE TABLE roles(code TEXT PRIMARY KEY,name TEXT NOT NULL);
CREATE TABLE permissions(code TEXT PRIMARY KEY,label TEXT NOT NULL);
CREATE TABLE role_permissions(role TEXT NOT NULL REFERENCES roles(code),permission TEXT NOT NULL REFERENCES permissions(code),PRIMARY KEY(role,permission));
CREATE TABLE user_roles(user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL REFERENCES roles(code),PRIMARY KEY(user_id,role));
CREATE TABLE counters(key TEXT PRIMARY KEY,value INTEGER NOT NULL);
ALTER TABLE records ADD COLUMN code TEXT;
ALTER TABLE records ADD COLUMN access TEXT NOT NULL DEFAULT 'restricted' CHECK(access IN('public','internal','restricted','confidential'));
CREATE UNIQUE INDEX record_code ON records(code);
CREATE TABLE journey(project_id TEXT NOT NULL REFERENCES records(id),step INTEGER NOT NULL,version INTEGER NOT NULL DEFAULT 1,progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 100),assignee TEXT REFERENCES users(id),deadline TEXT,note TEXT NOT NULL DEFAULT '',checklist TEXT NOT NULL DEFAULT '[]',PRIMARY KEY(project_id,step));
CREATE TABLE comments(id TEXT PRIMARY KEY,record_id TEXT NOT NULL REFERENCES records(id),user_id TEXT NOT NULL REFERENCES users(id),content TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE votes(record_id TEXT REFERENCES records(id),user_id TEXT REFERENCES users(id),PRIMARY KEY(record_id,user_id));
CREATE TABLE form_responses(id TEXT PRIMARY KEY,form_id TEXT NOT NULL REFERENCES records(id),user_id TEXT REFERENCES users(id),answers TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reset_tokens(hash TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),expires INTEGER NOT NULL);
ALTER TABLE reviews ADD COLUMN deadline TEXT;
ALTER TABLE reviews ADD COLUMN rubric TEXT NOT NULL DEFAULT '{}';
ALTER TABLE reviews ADD COLUMN response TEXT NOT NULL DEFAULT '';
ALTER TABLE files ADD COLUMN deleted INTEGER NOT NULL DEFAULT 0;
ALTER TABLE files ADD COLUMN version INTEGER NOT NULL DEFAULT 1;
CREATE TABLE response_files(id TEXT PRIMARY KEY,form_id TEXT NOT NULL REFERENCES records(id),user_id TEXT NOT NULL REFERENCES users(id),object_key TEXT NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,size INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE metrics(record_id TEXT PRIMARY KEY REFERENCES records(id),views INTEGER NOT NULL DEFAULT 0,downloads INTEGER NOT NULL DEFAULT 0);
ALTER TABLE files ADD COLUMN journey_step INTEGER;
CREATE TABLE outbox(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),channel TEXT NOT NULL DEFAULT 'email',subject TEXT NOT NULL,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
